onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb_dlx/dut/fetch_inst/addr_out
add wave -noupdate /tb_dlx/dut/decode_inst/pc_in
add wave -noupdate /tb_dlx/dut/fetch_inst/instr_out
add wave -noupdate /tb_dlx/dut/decode_inst/instr_in
add wave -noupdate /tb_dlx/dut/decode_inst/instr_out
add wave -noupdate /tb_dlx/dut/execute_inst/instr_in
add wave -noupdate /tb_dlx/dut/execute_inst/instr_out
add wave -noupdate /tb_dlx/dut/memory_inst/instr_in
add wave -noupdate /tb_dlx/dut/memory_inst/instr_out
add wave -noupdate /tb_dlx/dut/writeback_inst/instr_in
add wave -noupdate /tb_dlx/dut/decode_inst/pc_out
add wave -noupdate /tb_dlx/dut/execute_inst/pc_in
add wave -noupdate /tb_dlx/dut/execute_inst/pc_src_out
add wave -noupdate /tb_dlx/dut/execute_inst/pc_target_out
add wave -noupdate /tb_dlx/dut/decode_inst/stall_in
add wave -noupdate /tb_dlx/dut/decode_inst/flush_in
add wave -noupdate /tb_dlx/dut/fetch_inst/clk
add wave -noupdate /tb_dlx/dut/fetch_inst/rst
add wave -noupdate /tb_dlx/dut/fetch_inst/mux_sel
add wave -noupdate /tb_dlx/dut/fetch_inst/jump_addr
add wave -noupdate /tb_dlx/dut/fetch_inst/pc_enable
add wave -noupdate /tb_dlx/dut/fetch_inst/pc_f
add wave -noupdate /tb_dlx/dut/fetch_inst/pc_next
add wave -noupdate /tb_dlx/dut/decode_inst/clk
add wave -noupdate /tb_dlx/dut/decode_inst/rst
add wave -noupdate /tb_dlx/dut/decode_inst/wb_we
add wave -noupdate /tb_dlx/dut/decode_inst/wb_addr
add wave -noupdate /tb_dlx/dut/decode_inst/wb_data
add wave -noupdate /tb_dlx/dut/decode_inst/regA_out
add wave -noupdate /tb_dlx/dut/decode_inst/regB_out
add wave -noupdate /tb_dlx/dut/decode_inst/imm_out
add wave -noupdate /tb_dlx/dut/decode_inst/rs1_out
add wave -noupdate /tb_dlx/dut/decode_inst/rs2_out
add wave -noupdate /tb_dlx/dut/decode_inst/rd_out
add wave -noupdate /tb_dlx/dut/decode_inst/RegWrite_out
add wave -noupdate /tb_dlx/dut/decode_inst/ALUSrc_out
add wave -noupdate /tb_dlx/dut/decode_inst/Branch_out
add wave -noupdate /tb_dlx/dut/decode_inst/Jump_out
add wave -noupdate /tb_dlx/dut/decode_inst/ALUOp_out
add wave -noupdate /tb_dlx/dut/decode_inst/opcode_out
add wave -noupdate /tb_dlx/dut/decode_inst/opcode
add wave -noupdate /tb_dlx/dut/decode_inst/rd
add wave -noupdate /tb_dlx/dut/decode_inst/rs1
add wave -noupdate /tb_dlx/dut/decode_inst/rs2
add wave -noupdate /tb_dlx/dut/decode_inst/imm16
add wave -noupdate /tb_dlx/dut/decode_inst/regA
add wave -noupdate /tb_dlx/dut/decode_inst/regB
add wave -noupdate /tb_dlx/dut/decode_inst/imm_ext
add wave -noupdate /tb_dlx/dut/decode_inst/imm_zero_ext
add wave -noupdate /tb_dlx/dut/decode_inst/RegWrite
add wave -noupdate /tb_dlx/dut/decode_inst/ALUSrc
add wave -noupdate /tb_dlx/dut/decode_inst/Branch
add wave -noupdate /tb_dlx/dut/decode_inst/Jump
add wave -noupdate /tb_dlx/dut/decode_inst/ALUOp
add wave -noupdate /tb_dlx/dut/decode_inst/ra2_mux
add wave -noupdate /tb_dlx/dut/decode_inst/rs1_actual
add wave -noupdate /tb_dlx/dut/decode_inst/jump_addr
add wave -noupdate /tb_dlx/dut/decode_inst/jump_reg
add wave -noupdate /tb_dlx/dut/decode_inst/imm_actual
add wave -noupdate /tb_dlx/dut/execute_inst/clk
add wave -noupdate /tb_dlx/dut/execute_inst/rst
add wave -noupdate /tb_dlx/dut/execute_inst/regA_in
add wave -noupdate /tb_dlx/dut/execute_inst/regB_in
add wave -noupdate /tb_dlx/dut/execute_inst/imm_in
add wave -noupdate /tb_dlx/dut/execute_inst/rd_in
add wave -noupdate /tb_dlx/dut/execute_inst/RegWrite_in
add wave -noupdate /tb_dlx/dut/execute_inst/ALUSrc_in
add wave -noupdate /tb_dlx/dut/execute_inst/Branch_in
add wave -noupdate /tb_dlx/dut/execute_inst/Jump_in
add wave -noupdate /tb_dlx/dut/execute_inst/ALUOp_in
add wave -noupdate /tb_dlx/dut/execute_inst/opcode_in
add wave -noupdate /tb_dlx/dut/execute_inst/forwardA
add wave -noupdate /tb_dlx/dut/execute_inst/forwardB
add wave -noupdate /tb_dlx/dut/execute_inst/alu_forward
add wave -noupdate /tb_dlx/dut/execute_inst/wb_forward
add wave -noupdate /tb_dlx/dut/execute_inst/alu_result_out
add wave -noupdate /tb_dlx/dut/execute_inst/rd_out
add wave -noupdate /tb_dlx/dut/execute_inst/RegWrite_out
add wave -noupdate /tb_dlx/dut/execute_inst/regB_out
add wave -noupdate /tb_dlx/dut/execute_inst/rs1_in
add wave -noupdate /tb_dlx/dut/execute_inst/rs2_in
add wave -noupdate /tb_dlx/dut/execute_inst/operandB
add wave -noupdate /tb_dlx/dut/execute_inst/alu_res
add wave -noupdate /tb_dlx/dut/execute_inst/pc_target
add wave -noupdate /tb_dlx/dut/execute_inst/pc_src
add wave -noupdate /tb_dlx/dut/execute_inst/aluA
add wave -noupdate /tb_dlx/dut/execute_inst/aluB_pre
add wave -noupdate /tb_dlx/dut/memory_inst/clk
add wave -noupdate /tb_dlx/dut/memory_inst/rst
add wave -noupdate /tb_dlx/dut/memory_inst/alu_result_in
add wave -noupdate /tb_dlx/dut/memory_inst/regB_data_in
add wave -noupdate /tb_dlx/dut/memory_inst/reg_write_in
add wave -noupdate /tb_dlx/dut/memory_inst/rd_in
add wave -noupdate /tb_dlx/dut/memory_inst/mem_data_out
add wave -noupdate /tb_dlx/dut/memory_inst/alu_out
add wave -noupdate /tb_dlx/dut/memory_inst/rd_out
add wave -noupdate /tb_dlx/dut/memory_inst/reg_write_out
add wave -noupdate /tb_dlx/dut/memory_inst/opcode
add wave -noupdate /tb_dlx/dut/memory_inst/ram_q
add wave -noupdate /tb_dlx/dut/memory_inst/wren
add wave -noupdate /tb_dlx/dut/writeback_inst/mem_data_in
add wave -noupdate /tb_dlx/dut/writeback_inst/alu_data_in
add wave -noupdate /tb_dlx/dut/writeback_inst/rd_in
add wave -noupdate /tb_dlx/dut/writeback_inst/reg_write_in
add wave -noupdate /tb_dlx/dut/writeback_inst/wb_we
add wave -noupdate /tb_dlx/dut/writeback_inst/wb_addr
add wave -noupdate /tb_dlx/dut/writeback_inst/wb_data
add wave -noupdate /tb_dlx/dut/writeback_inst/opcode
add wave -noupdate /tb_dlx/dut/writeback_inst/wb_mux
add wave -noupdate /tb_dlx/dut/decode_inst/rf_inst/clk
add wave -noupdate /tb_dlx/dut/decode_inst/rf_inst/we
add wave -noupdate /tb_dlx/dut/decode_inst/rf_inst/ra1
add wave -noupdate /tb_dlx/dut/decode_inst/rf_inst/ra2
add wave -noupdate /tb_dlx/dut/decode_inst/rf_inst/wa
add wave -noupdate /tb_dlx/dut/decode_inst/rf_inst/wd
add wave -noupdate /tb_dlx/dut/decode_inst/rf_inst/rd1
add wave -noupdate /tb_dlx/dut/decode_inst/rf_inst/rd2
add wave -noupdate -expand /tb_dlx/dut/decode_inst/rf_inst/ram_block
add wave -noupdate /tb_dlx/dut/clk
add wave -noupdate /tb_dlx/dut/rst
add wave -noupdate /tb_dlx/dut/instr_f
add wave -noupdate /tb_dlx/dut/pc_f
add wave -noupdate /tb_dlx/dut/regA_d
add wave -noupdate /tb_dlx/dut/regB_d
add wave -noupdate /tb_dlx/dut/imm_d
add wave -noupdate /tb_dlx/dut/rd_d
add wave -noupdate /tb_dlx/dut/pc_d
add wave -noupdate /tb_dlx/dut/RegWrite_d
add wave -noupdate /tb_dlx/dut/ALUSrc_d
add wave -noupdate /tb_dlx/dut/Branch_d
add wave -noupdate /tb_dlx/dut/Jump_d
add wave -noupdate /tb_dlx/dut/ALUOp_d
add wave -noupdate /tb_dlx/dut/opcode_d
add wave -noupdate /tb_dlx/dut/instr_d
add wave -noupdate /tb_dlx/dut/alu_e
add wave -noupdate /tb_dlx/dut/rd_e
add wave -noupdate /tb_dlx/dut/regB_e
add wave -noupdate /tb_dlx/dut/RegWrite_e
add wave -noupdate /tb_dlx/dut/instr_e
add wave -noupdate /tb_dlx/dut/pc_target_e
add wave -noupdate /tb_dlx/dut/pc_src_e
add wave -noupdate /tb_dlx/dut/mem_data_m
add wave -noupdate /tb_dlx/dut/alu_m
add wave -noupdate /tb_dlx/dut/rd_m
add wave -noupdate /tb_dlx/dut/RegWrite_m
add wave -noupdate /tb_dlx/dut/instr_m
add wave -noupdate /tb_dlx/dut/wb_we
add wave -noupdate /tb_dlx/dut/wb_addr
add wave -noupdate /tb_dlx/dut/wb_data
add wave -noupdate /tb_dlx/dut/rs1_d
add wave -noupdate /tb_dlx/dut/rs2_d
add wave -noupdate /tb_dlx/dut/forwardA
add wave -noupdate /tb_dlx/dut/forwardB
add wave -noupdate /tb_dlx/dut/rs1_exec
add wave -noupdate /tb_dlx/dut/rs2_exec
add wave -noupdate /tb_dlx/dut/is_load_e
add wave -noupdate /tb_dlx/dut/stall
add wave -noupdate /tb_dlx/dut/pc_enable_s
add wave -noupdate /tb_dlx/dut/flush
add wave -noupdate /tb_dlx/dut/instr_f_mux
add wave -noupdate /tb_dlx/dut/instr_d_mux
add wave -noupdate /tb_dlx/dut/RegWrite_d_mux
add wave -noupdate /tb_dlx/dut/Branch_d_mux
add wave -noupdate /tb_dlx/dut/Jump_d_mux
add wave -noupdate /tb_dlx/dut/ALUSrc_d_mux
add wave -noupdate /tb_dlx/dut/ALUOp_d_mux
add wave -noupdate /tb_dlx/dut/rd_d_mux
add wave -noupdate /tb_dlx/dut/regA_d_mux
add wave -noupdate /tb_dlx/dut/regB_d_mux
add wave -noupdate /tb_dlx/dut/imm_d_mux
add wave -noupdate /tb_dlx/dut/opcode_d_mux
add wave -noupdate /tb_dlx/dut/pc_d_mux
add wave -noupdate /tb_dlx/dut/flush_d
add wave -noupdate /tb_dlx/dut/fifo1_data_in
add wave -noupdate /tb_dlx/dut/fifo1_data_out
add wave -noupdate /tb_dlx/dut/fifo1_wr
add wave -noupdate /tb_dlx/dut/fifo1_full
add wave -noupdate /tb_dlx/dut/fifo1_empty
add wave -noupdate /tb_dlx/dut/fifo2_data_in
add wave -noupdate /tb_dlx/dut/fifo2_data_out
add wave -noupdate /tb_dlx/dut/fifo2_wr
add wave -noupdate /tb_dlx/dut/fifo2_rd
add wave -noupdate /tb_dlx/dut/fifo2_full
add wave -noupdate /tb_dlx/dut/fifo2_empty
add wave -noupdate /tb_dlx/dut/pe_fifo_rd
add wave -noupdate /tb_dlx/dut/uart_fifo_rd
add wave -noupdate /tb_dlx/dut/fifo1_inst/clock
add wave -noupdate -radix decimal /tb_dlx/dut/fifo1_inst/data
add wave -noupdate /tb_dlx/dut/fifo1_inst/rdreq
add wave -noupdate /tb_dlx/dut/fifo1_inst/wrreq
add wave -noupdate /tb_dlx/dut/fifo1_inst/empty
add wave -noupdate /tb_dlx/dut/fifo1_inst/full
add wave -noupdate /tb_dlx/dut/fifo1_inst/q
add wave -noupdate /tb_dlx/dut/fifo1_inst/usedw
add wave -noupdate /tb_dlx/dut/fifo1_inst/sub_wire0
add wave -noupdate /tb_dlx/dut/fifo1_inst/sub_wire1
add wave -noupdate /tb_dlx/dut/fifo1_inst/sub_wire2
add wave -noupdate /tb_dlx/dut/fifo1_inst/sub_wire3
add wave -noupdate /tb_dlx/dut/uart_inst/CLOCK_50
add wave -noupdate /tb_dlx/dut/uart_inst/RX
add wave -noupdate /tb_dlx/dut/uart_inst/TX
add wave -noupdate /tb_dlx/dut/uart_inst/fifo_data_in
add wave -noupdate /tb_dlx/dut/uart_inst/fifo_empty
add wave -noupdate /tb_dlx/dut/uart_inst/fifo_rd
add wave -noupdate /tb_dlx/dut/uart_inst/uart_clk
add wave -noupdate /tb_dlx/dut/uart_inst/rx_data
add wave -noupdate /tb_dlx/dut/uart_inst/rx_done
add wave -noupdate /tb_dlx/dut/uart_inst/uart_tx_busy
add wave -noupdate /tb_dlx/dut/uart_inst/tx_ctrl_state
add wave -noupdate /tb_dlx/dut/uart_inst/tx_start
add wave -noupdate /tb_dlx/dut/uart_inst/tx_data
add wave -noupdate /tb_dlx/clk
add wave -noupdate /tb_dlx/rst
add wave -noupdate /tb_dlx/TX
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {330000 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 245
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {242 ns} {418 ns}
