onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb_dlx/dut/fetch_inst/addr_out
add wave -noupdate /tb_dlx/dut/decode_inst/pc_in
add wave -noupdate /tb_dlx/dut/fetch_inst/instr_out
add wave -noupdate /tb_dlx/dut/decode_inst/instr_in
add wave -noupdate /tb_dlx/dut/decode_inst/instr_out
add wave -noupdate /tb_dlx/dut/execute_inst/instr_in
add wave -noupdate /tb_dlx/dut/execute_inst/instr_out
add wave -noupdate /tb_dlx/dut/memory_inst/instr_in
add wave -noupdate /tb_dlx/dut/memory_inst/instr_out
add wave -noupdate /tb_dlx/dut/writeback_inst/instr_in
add wave -noupdate /tb_dlx/dut/decode_inst/pc_out
add wave -noupdate /tb_dlx/dut/execute_inst/pc_in
add wave -noupdate /tb_dlx/dut/execute_inst/pc_src_out
add wave -noupdate /tb_dlx/dut/execute_inst/pc_target_out
add wave -noupdate /tb_dlx/dut/decode_inst/stall_in
add wave -noupdate /tb_dlx/dut/decode_inst/flush_in
add wave -noupdate /tb_dlx/dut/fetch_inst/clk
add wave -noupdate /tb_dlx/dut/fetch_inst/rst
add wave -noupdate /tb_dlx/dut/fetch_inst/mux_sel
add wave -noupdate /tb_dlx/dut/fetch_inst/jump_addr
add wave -noupdate /tb_dlx/dut/fetch_inst/pc_enable
add wave -noupdate /tb_dlx/dut/fetch_inst/pc_f
add wave -noupdate /tb_dlx/dut/fetch_inst/pc_next
add wave -noupdate /tb_dlx/dut/decode_inst/clk
add wave -noupdate /tb_dlx/dut/decode_inst/rst
add wave -noupdate /tb_dlx/dut/decode_inst/wb_we
add wave -noupdate /tb_dlx/dut/decode_inst/wb_addr
add wave -noupdate /tb_dlx/dut/decode_inst/wb_data
add wave -noupdate /tb_dlx/dut/decode_inst/regA_out
add wave -noupdate /tb_dlx/dut/decode_inst/regB_out
add wave -noupdate /tb_dlx/dut/decode_inst/imm_out
add wave -noupdate /tb_dlx/dut/decode_inst/rs1_out
add wave -noupdate /tb_dlx/dut/decode_inst/rs2_out
add wave -noupdate /tb_dlx/dut/decode_inst/rd_out
add wave -noupdate /tb_dlx/dut/decode_inst/RegWrite_out
add wave -noupdate /tb_dlx/dut/decode_inst/ALUSrc_out
add wave -noupdate /tb_dlx/dut/decode_inst/Branch_out
add wave -noupdate /tb_dlx/dut/decode_inst/Jump_out
add wave -noupdate /tb_dlx/dut/decode_inst/ALUOp_out
add wave -noupdate /tb_dlx/dut/decode_inst/opcode_out
add wave -noupdate /tb_dlx/dut/decode_inst/opcode
add wave -noupdate /tb_dlx/dut/decode_inst/rd
add wave -noupdate /tb_dlx/dut/decode_inst/rs1
add wave -noupdate /tb_dlx/dut/decode_inst/rs2
add wave -noupdate /tb_dlx/dut/decode_inst/imm16
add wave -noupdate /tb_dlx/dut/decode_inst/regA
add wave -noupdate /tb_dlx/dut/decode_inst/regB
add wave -noupdate /tb_dlx/dut/decode_inst/imm_ext
add wave -noupdate /tb_dlx/dut/decode_inst/imm_zero_ext
add wave -noupdate /tb_dlx/dut/decode_inst/RegWrite
add wave -noupdate /tb_dlx/dut/decode_inst/ALUSrc
add wave -noupdate /tb_dlx/dut/decode_inst/Branch
add wave -noupdate /tb_dlx/dut/decode_inst/Jump
add wave -noupdate /tb_dlx/dut/decode_inst/ALUOp
add wave -noupdate /tb_dlx/dut/decode_inst/ra2_mux
add wave -noupdate /tb_dlx/dut/decode_inst/rs1_actual
add wave -noupdate /tb_dlx/dut/decode_inst/jump_addr
add wave -noupdate /tb_dlx/dut/decode_inst/jump_reg
add wave -noupdate /tb_dlx/dut/decode_inst/imm_actual
add wave -noupdate /tb_dlx/dut/execute_inst/clk
add wave -noupdate /tb_dlx/dut/execute_inst/rst
add wave -noupdate /tb_dlx/dut/execute_inst/regA_in
add wave -noupdate /tb_dlx/dut/execute_inst/regB_in
add wave -noupdate /tb_dlx/dut/execute_inst/imm_in
add wave -noupdate /tb_dlx/dut/execute_inst/rd_in
add wave -noupdate /tb_dlx/dut/execute_inst/RegWrite_in
add wave -noupdate /tb_dlx/dut/execute_inst/ALUSrc_in
add wave -noupdate /tb_dlx/dut/execute_inst/Branch_in
add wave -noupdate /tb_dlx/dut/execute_inst/Jump_in
add wave -noupdate /tb_dlx/dut/execute_inst/ALUOp_in
add wave -noupdate /tb_dlx/dut/execute_inst/opcode_in
add wave -noupdate /tb_dlx/dut/execute_inst/forwardA
add wave -noupdate /tb_dlx/dut/execute_inst/forwardB
add wave -noupdate /tb_dlx/dut/execute_inst/alu_forward
add wave -noupdate /tb_dlx/dut/execute_inst/wb_forward
add wave -noupdate /tb_dlx/dut/execute_inst/alu_result_out
add wave -noupdate /tb_dlx/dut/execute_inst/rd_out
add wave -noupdate /tb_dlx/dut/execute_inst/RegWrite_out
add wave -noupdate /tb_dlx/dut/execute_inst/regB_out
add wave -noupdate /tb_dlx/dut/execute_inst/rs1_in
add wave -noupdate /tb_dlx/dut/execute_inst/rs2_in
add wave -noupdate /tb_dlx/dut/execute_inst/operandB
add wave -noupdate /tb_dlx/dut/execute_inst/alu_res
add wave -noupdate /tb_dlx/dut/execute_inst/pc_target
add wave -noupdate /tb_dlx/dut/execute_inst/pc_src
add wave -noupdate /tb_dlx/dut/execute_inst/aluA
add wave -noupdate /tb_dlx/dut/execute_inst/aluB_pre
add wave -noupdate /tb_dlx/dut/memory_inst/clk
add wave -noupdate /tb_dlx/dut/memory_inst/rst
add wave -noupdate /tb_dlx/dut/memory_inst/alu_result_in
add wave -noupdate /tb_dlx/dut/memory_inst/regB_data_in
add wave -noupdate /tb_dlx/dut/memory_inst/reg_write_in
add wave -noupdate /tb_dlx/dut/memory_inst/rd_in
add wave -noupdate /tb_dlx/dut/memory_inst/mem_data_out
add wave -noupdate /tb_dlx/dut/memory_inst/alu_out
add wave -noupdate /tb_dlx/dut/memory_inst/rd_out
add wave -noupdate /tb_dlx/dut/memory_inst/reg_write_out
add wave -noupdate /tb_dlx/dut/memory_inst/opcode
add wave -noupdate /tb_dlx/dut/memory_inst/ram_q
add wave -noupdate /tb_dlx/dut/memory_inst/wren
add wave -noupdate /tb_dlx/dut/writeback_inst/mem_data_in
add wave -noupdate /tb_dlx/dut/writeback_inst/alu_data_in
add wave -noupdate /tb_dlx/dut/writeback_inst/rd_in
add wave -noupdate /tb_dlx/dut/writeback_inst/reg_write_in
add wave -noupdate /tb_dlx/dut/writeback_inst/wb_we
add wave -noupdate /tb_dlx/dut/writeback_inst/wb_addr
add wave -noupdate /tb_dlx/dut/writeback_inst/wb_data
add wave -noupdate /tb_dlx/dut/writeback_inst/opcode
add wave -noupdate /tb_dlx/dut/writeback_inst/wb_mux
add wave -noupdate /tb_dlx/dut/decode_inst/rf_inst/clk
add wave -noupdate /tb_dlx/dut/decode_inst/rf_inst/we
add wave -noupdate /tb_dlx/dut/decode_inst/rf_inst/ra1
add wave -noupdate /tb_dlx/dut/decode_inst/rf_inst/ra2
add wave -noupdate /tb_dlx/dut/decode_inst/rf_inst/wa
add wave -noupdate /tb_dlx/dut/decode_inst/rf_inst/wd
add wave -noupdate /tb_dlx/dut/decode_inst/rf_inst/rd1
add wave -noupdate /tb_dlx/dut/decode_inst/rf_inst/rd2
add wave -noupdate -expand /tb_dlx/dut/decode_inst/rf_inst/ram_block
add wave -noupdate /tb_dlx/dut/fifo1_inst/clk
add wave -noupdate /tb_dlx/dut/fifo1_inst/rst
add wave -noupdate /tb_dlx/dut/fifo1_inst/wr_en
add wave -noupdate /tb_dlx/dut/fifo1_inst/rd_en
add wave -noupdate /tb_dlx/dut/fifo1_inst/data_in
add wave -noupdate /tb_dlx/dut/fifo1_inst/data_out
add wave -noupdate /tb_dlx/dut/fifo1_inst/full
add wave -noupdate /tb_dlx/dut/fifo1_inst/empty
add wave -noupdate /tb_dlx/dut/fifo1_inst/mem
add wave -noupdate /tb_dlx/dut/fifo1_inst/wptr
add wave -noupdate /tb_dlx/dut/fifo1_inst/rptr
add wave -noupdate /tb_dlx/dut/fifo1_inst/count
add wave -noupdate /tb_dlx/dut/fifo1_inst/full_s
add wave -noupdate /tb_dlx/dut/fifo1_inst/empty_s
add wave -noupdate /tb_dlx/dut/print_engine_inst/clk
add wave -noupdate /tb_dlx/dut/print_engine_inst/rst
add wave -noupdate /tb_dlx/dut/print_engine_inst/fifo_in_data
add wave -noupdate /tb_dlx/dut/print_engine_inst/fifo_in_empty
add wave -noupdate /tb_dlx/dut/print_engine_inst/fifo_in_rd
add wave -noupdate /tb_dlx/dut/print_engine_inst/fifo_out_data
add wave -noupdate /tb_dlx/dut/print_engine_inst/fifo_out_wr
add wave -noupdate /tb_dlx/dut/print_engine_inst/fifo_out_full
add wave -noupdate /tb_dlx/dut/print_engine_inst/state
add wave -noupdate /tb_dlx/dut/print_engine_inst/pkt_type
add wave -noupdate /tb_dlx/dut/print_engine_inst/value_reg
add wave -noupdate /tb_dlx/dut/print_engine_inst/is_negative
add wave -noupdate /tb_dlx/dut/print_engine_inst/numer_reg
add wave -noupdate /tb_dlx/dut/print_engine_inst/quotient
add wave -noupdate /tb_dlx/dut/print_engine_inst/remainder
add wave -noupdate /tb_dlx/dut/print_engine_inst/div_valid_shift
add wave -noupdate /tb_dlx/dut/print_engine_inst/div_start
add wave -noupdate /tb_dlx/dut/print_engine_inst/digits
add wave -noupdate /tb_dlx/dut/print_engine_inst/digit_count
add wave -noupdate /tb_dlx/dut/print_engine_inst/out_index
add wave -noupdate /tb_dlx/dut/fifo2_inst/clk
add wave -noupdate /tb_dlx/dut/fifo2_inst/rst
add wave -noupdate /tb_dlx/dut/fifo2_inst/wr_en
add wave -noupdate /tb_dlx/dut/fifo2_inst/rd_en
add wave -noupdate /tb_dlx/dut/fifo2_inst/data_in
add wave -noupdate /tb_dlx/dut/fifo2_inst/data_out
add wave -noupdate /tb_dlx/dut/fifo2_inst/full
add wave -noupdate /tb_dlx/dut/fifo2_inst/empty
add wave -noupdate /tb_dlx/dut/fifo2_inst/mem
add wave -noupdate /tb_dlx/dut/fifo2_inst/wptr
add wave -noupdate /tb_dlx/dut/fifo2_inst/rptr
add wave -noupdate /tb_dlx/dut/fifo2_inst/count
add wave -noupdate /tb_dlx/dut/fifo2_inst/full_s
add wave -noupdate /tb_dlx/dut/fifo2_inst/empty_s
add wave -noupdate /tb_dlx/dut/uart_inst/CLOCK_50
add wave -noupdate /tb_dlx/dut/uart_inst/RX
add wave -noupdate /tb_dlx/dut/uart_inst/TX
add wave -noupdate /tb_dlx/dut/uart_inst/fifo_data_in
add wave -noupdate /tb_dlx/dut/uart_inst/fifo_empty
add wave -noupdate /tb_dlx/dut/uart_inst/fifo_rd
add wave -noupdate /tb_dlx/dut/uart_inst/uart_clk
add wave -noupdate /tb_dlx/dut/uart_inst/rx_data
add wave -noupdate /tb_dlx/dut/uart_inst/rx_done
add wave -noupdate /tb_dlx/dut/uart_inst/tx_busy
add wave -noupdate /tb_dlx/dut/uart_inst/tx_start
add wave -noupdate /tb_dlx/dut/uart_inst/tx_data
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {310 ns} 0}
quietly wave cursor active 1
configure wave -namecolwidth 245
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ns} {310 ns}
